platform: nodejs_lib
shared:
  notifications:
    email: cards-dev@yahoo-inc.com

  steps:
    lint:
      description: "Custom lint using jshint instead of yhint"
      command: "./script/lint.sh"
    test:
      script: "screwdriver"

jobs:
  component:
    profile: [init, lint, test, publish]
    steps:
      publish:
        bump_version: false
  pull-request:
    profile: [init, lint, test]
