platform: nodejs_lib
shared:
  notifications:
    email: cards-dev@yahoo-inc.com

  steps:
    lint:
      description: "Custom lint using jshint instead of yhint"
      command: "./script/lint.sh"

    test:
      description: "Custom test using Whiskey"
      command: "./script/test.sh"

  plugins:
    coverage:
      enabled: false
      type: lcov
      parameters:
        info_path: artifacts/coverage
        report_path: artifacts/coverage/lcov-report
    test_results:
      type: tap
      parameters:
        path: artifacts/test


jobs:
  component:
    profile: [init, lint, test, publish]
    steps:
      publish:
        bump_version: false
  pull-request:
    profile: [init, lint, test]
