var fs = require('fs')
  , path = require('path')
  , async = require('async')
  , mkdirp = require('mkdirp')
  , tmp = require('tmp')
  , sys = require('sys')
  , exec = require('child_process').exec
  , spawn = require('child_process').spawn
  , card = require('../card')
  , compile = require('../compile')
  ;

module.exports = function(options) {
  var srcDir = process.cwd();
  var tmpDir = null;
  var info = null;

  async.waterfall([
    // create temp directory
    function(callback) {
      tmp.dir({unsafeCleanup: !options.n}, function(err, path) {
        if (err) {
          return callback(err);
        }
        tmpDir = path;
        console.log("Working directory: ", tmpDir);
        callback();
      });
    },

    // Load card info
    function(callback) {
      card.read(srcDir, callback);
    },

    // Compile card
    function(c, callback) {
      info = c;
      compile.compileCard({
        dir: srcDir,
        name: c.name
      }, 'javascript', callback);
    },

    // Write main.js to lib/index.js
    function(files, callback) {
      var d = path.join(tmpDir, 'lib');
      mkdirp(d, function(err) {
        fs.writeFile(path.join(d, 'index.js'), files['main.js'], callback);
      });
    },

    // Write .npmignore
    function(callback) {
      fs.writeFile(path.join(tmpDir, '.npmignore'), 'card.json\nsrc/\n', callback);
    },

    // Write package.json
    function(callback) {
      fs.writeFile(path.join(tmpDir, 'package.json'), JSON.stringify({
        name: "vizify-card-" + info.name,
        version: info.version,
        description: 'Autogenerated browserify module',
        main: 'lib/index.js',
        yahoo: {
          bugzilla: {
            product: "TODO",
            component: "General"
          },
          custodian: {
            email: "cards-dev@yahoo-inc.com",
            url: "https://git.corp.yahoo.com/vizify/tool"
          }
        }}, null, 2), callback);
    },

    // Run npm publish unless dry run option (-n) is passed
    function(callback) {
      if (options['n']) {
        console.log("Not publishing. Leaving temp files in: " + tmpDir);
      } else {
        var cmd = "ynpm publish " + tmpDir;
        console.log("Executing: " + cmd);
        publish = spawn('ynpm', ['publish'], {cwd: tmpDir, stdio: 'inherit'});
        publish.on('close', function (code) {
          console.log('Child process exited with code ' + code);
        });
      }
      callback();
    }
  ], function(err) {
    if (err) {
      console.error(err.message);
      process.exit(1);
    }
  });
};
module.exports.doc = "Publish to ynpm.\n\t-n : Dry run - doesn't run ynpm publish or cleanup temp files.";
